site_name: Rae-Phd-Projects
nav:
  - Home: 'index.md'
  - About: 'about.md'  
  - Protein Geometry:
    - Overview: geom/overview.md
  - Density and Potential Maps:
    - Overview: maps/overview.md
  - Interpolation:
    - Overview: interp/overview
  - TrivialDivergence:
    - Overview: trivial/overview.md  
theme:
  name: material
  logo: assets/density.png
  favicon: assets/cross.png
  palette:
    primary: indigo  
    accent: pink
  features:
    - content.code.copy
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
