site_name: Rae-Phd-Projects
nav:
  - Home: 'index.md'  
  - Protein Geometry:
    - Overview: geometry/overview.md
    - Python library: geometry/py-lib.md
    - Web application: geometry/prometry.md
    - Results: geometry/results.md
  - Density and Potential Maps:
    - Overview: maps/overview.md
    - Density: maps/density.md
    - Radient: maps/radient.md
    - Laplacian: maps/laplacian.md    
    - Python library: maps/py-lib.md
    - Colab demo: maps/colab.py
    - Results: maps/results.md
  - Interpolation:
    - Overview: interpolation/overview
    - N-dim M-Poly: interpolation/alcraft.md
    - Python library: interpolation/py-lib.md
    - Colab demo: interpolation/colab.py
    - Results: interpolation/results.md
  - Trivial Divergence:
    - Overview: trivial/overview.md  
    - Method: trivial/method.md  
    - Python library: trivial/py-lib.md
    - Colab demo: trivial/colab.py
    - Results: trivial/results.md
  - About: 'about.md'  
  - References: 'references.md'  
theme:
  name: material
  logo: assets/density.png
  favicon: assets/cross.png
  palette:
    primary: indigo  
    accent: pink
  features:
    - content.code.copy
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
